import type { Question, Expectation, SessionReflection, Deliverable, Milestone } from './types'

export const seedQuestions: Question[] = [
  {
    id: 'q1',
    text: 'Do group presentations count towards the individual participation score, or only in-class contributions?',
    tag: 'criteria',
    anonymous: false,
    authorName: 'Lena Visser',
    createdAt: '2025-05-14T10:23:00Z',
    answered: true,
    answers: [
      {
        id: 'a1',
        text: 'Group presentations count for 40% of the presentation grade. Individual participation is tracked separately through your in-class check-ins and reflection submissions.',
        authorName: 'Dr. Brouwer',
        createdAt: '2025-05-14T14:00:00Z',
      },
    ],
  },
  {
    id: 'q2',
    text: 'Can we reference case studies from outside the provided reading list?',
    tag: 'content',
    anonymous: false,
    authorName: 'Marco de Vries',
    createdAt: '2025-05-15T09:45:00Z',
    answered: true,
    answers: [
      {
        id: 'a2',
        text: 'Yes! External case studies are encouraged. Just make sure to cite them properly using APA 7th edition and explicitly connect them to the course theory.',
        authorName: 'Dr. Brouwer',
        createdAt: '2025-05-15T11:30:00Z',
      },
    ],
  },
  {
    id: 'q3',
    text: 'Is there a word count minimum for the reflection submissions?',
    tag: 'logistics',
    anonymous: true,
    authorName: 'Anonymous',
    createdAt: '2025-05-17T16:10:00Z',
    answered: false,
    answers: [],
  },
  {
    id: 'q4',
    text: 'How is "stakeholder alignment" assessed in the Business Model deliverable? The rubric mentions it but the criteria feel vague.',
    tag: 'criteria',
    anonymous: false,
    authorName: 'Amara Osei',
    createdAt: '2025-05-18T11:20:00Z',
    answered: false,
    answers: [],
  },
  {
    id: 'q5',
    text: 'Will the session on Design Thinking be recorded if we miss it?',
    tag: 'logistics',
    anonymous: false,
    authorName: 'Finn Bakker',
    createdAt: '2025-05-19T08:55:00Z',
    answered: true,
    answers: [
      {
        id: 'a3',
        text: 'Sessions are not recorded as standard, but if you know in advance you will miss it, contact me and I can provide a written summary and extra reading. Please attend if at all possible — the application exercises are central.',
        authorName: 'Dr. Brouwer',
        createdAt: '2025-05-19T10:00:00Z',
      },
    ],
  },
  {
    id: 'q6',
    text: 'For the market analysis, should we focus on the Netherlands specifically or can we take a European market view?',
    tag: 'content',
    anonymous: false,
    authorName: 'Sofia Pereira',
    createdAt: '2025-05-20T14:30:00Z',
    answered: false,
    answers: [],
  },
]

export const seedExpectations: Expectation[] = [
  {
    id: 'e1',
    text: 'Weekly feedback on my progress reports, not just at the end of the period.',
    authorName: 'Lena Visser',
    createdAt: '2025-05-01T09:00:00Z',
    status: 'confirmed',
    lecturerNote: 'We check in on progress reports every Friday. Please submit by Thursday midnight.',
  },
  {
    id: 'e2',
    text: 'Clear examples of what a "good" vs "excellent" deliverable looks like before we submit.',
    authorName: 'Marco de Vries',
    createdAt: '2025-05-01T09:15:00Z',
    status: 'confirmed',
    lecturerNote: 'Exemplars are posted in the Criteria Transparency board. Updated each time a deliverable opens.',
  },
  {
    id: 'e3',
    text: 'Team conflict resolution guidance — our group dynamics are challenging and we need a framework.',
    authorName: 'Amara Osei',
    createdAt: '2025-05-02T10:30:00Z',
    status: 'revised',
    lecturerNote: 'Addressed in Session 3 (Team Dynamics). If issues persist, book a 15-min check-in with me.',
  },
  {
    id: 'e4',
    text: 'Know at least 2 weeks in advance when a deliverable is due, so we can plan around other courses.',
    authorName: 'Finn Bakker',
    createdAt: '2025-05-03T11:00:00Z',
    status: 'confirmed',
    lecturerNote: 'Full timeline is posted in the Milestones section and will not change without 2 weeks\' notice.',
  },
  {
    id: 'e5',
    text: 'More time for actual group work during sessions, less passive listening.',
    authorName: 'Sofia Pereira',
    createdAt: '2025-05-05T14:20:00Z',
    status: 'confirmed',
    lecturerNote: 'Restructured: 25 min theory, 35 min application, 10 min reflection. See the Learning Cycle board.',
  },
  {
    id: 'e6',
    text: 'An anonymous channel to flag group issues without affecting the team grade.',
    authorName: 'Anonymous',
    createdAt: '2025-05-06T16:00:00Z',
    status: 'pending',
  },
]

export const seedReflections: SessionReflection[] = [
  {
    id: 'r1',
    sessionNumber: 1,
    sessionTitle: 'Introduction to Business Innovation',
    text: 'The theory section was clear. I struggled a bit with the application exercise because I wasn\'t sure if we should use the case study company or our own idea. Clarifying this upfront would help.',
    authorName: 'Lena Visser',
    createdAt: '2025-05-07T16:30:00Z',
    mood: 'good',
  },
  {
    id: 'r2',
    sessionNumber: 2,
    sessionTitle: 'Stakeholder Mapping',
    text: 'The stakeholder mapping exercise was really practical. Working with a real company scenario helped a lot. I felt much more confident by the end.',
    authorName: 'Marco de Vries',
    createdAt: '2025-05-12T16:45:00Z',
    mood: 'great',
  },
  {
    id: 'r3',
    sessionNumber: 3,
    sessionTitle: 'Team Dynamics & Conflict',
    text: 'Useful session but we ran out of time during the application phase. Would have liked more time to work through the scenario fully before moving to reflection.',
    authorName: 'Amara Osei',
    createdAt: '2025-05-15T17:00:00Z',
    mood: 'neutral',
  },
]

export const seedDeliverables: Deliverable[] = [
  {
    id: 'd1',
    title: 'Business Case — Problem Framing',
    description: 'Define the innovation challenge, scope, and stakeholder context for your chosen company.',
    dueDate: '2025-06-02',
    criteria: [
      {
        id: 'c1',
        criterion: 'Problem definition clarity',
        excellent: 'Problem is sharply defined, scoped, and grounded in evidence from at least 3 sources.',
        good: 'Problem is clearly defined with evidence from 2 sources.',
        satisfactory: 'Problem is stated but lacks scope or supporting evidence.',
        insufficient: 'Problem is vague, missing, or not relevant to the assignment.',
        weight: 30,
      },
      {
        id: 'c2',
        criterion: 'Stakeholder analysis',
        excellent: 'All key stakeholders mapped; interests, power, and influence clearly analysed.',
        good: 'Main stakeholders identified with brief analysis of interests.',
        satisfactory: 'Stakeholders listed without meaningful analysis.',
        insufficient: 'Stakeholder analysis absent or clearly incomplete.',
        weight: 25,
      },
      {
        id: 'c3',
        criterion: 'Innovation angle',
        excellent: 'Innovation opportunity is compelling, well-justified, and feasible within constraints.',
        good: 'Innovation angle is relevant and reasonably justified.',
        satisfactory: 'Innovation angle is present but weakly argued.',
        insufficient: 'No clear innovation angle or irrelevant to the challenge.',
        weight: 25,
      },
      {
        id: 'c4',
        criterion: 'Professional presentation',
        excellent: 'Flawless formatting, APA citations, no grammar or spelling errors.',
        good: 'Minor formatting or citation issues; otherwise professional.',
        satisfactory: 'Several formatting or language errors that distract.',
        insufficient: 'Poor formatting, no citations, or significant language errors.',
        weight: 20,
      },
    ],
  },
  {
    id: 'd2',
    title: 'Prototype Pitch Presentation',
    description: 'Present your innovation concept as a 10-minute pitch to the class panel.',
    dueDate: '2025-06-20',
    criteria: [
      {
        id: 'c5',
        criterion: 'Concept clarity',
        excellent: 'Concept is immediately clear; audience could explain it back without prompting.',
        good: 'Concept is mostly clear with minor ambiguities.',
        satisfactory: 'Concept requires further explanation after the pitch.',
        insufficient: 'Concept is unclear or not effectively communicated.',
        weight: 30,
      },
      {
        id: 'c6',
        criterion: 'Business viability',
        excellent: 'Revenue model, target market, and competitive landscape fully addressed.',
        good: 'Most business dimensions addressed with minor gaps.',
        satisfactory: 'Basic business model outlined but incomplete.',
        insufficient: 'Business viability not addressed.',
        weight: 30,
      },
      {
        id: 'c7',
        criterion: 'Delivery & engagement',
        excellent: 'Confident, engaging delivery; handles panel questions with depth.',
        good: 'Clear delivery; handles most questions adequately.',
        satisfactory: 'Presentation is readable; some difficulty with questions.',
        insufficient: 'Poor delivery or unable to engage with panel questions.',
        weight: 25,
      },
      {
        id: 'c8',
        criterion: 'Visual design',
        excellent: 'Slides enhance the story; clean, consistent, professional design.',
        good: 'Slides are clear and mostly consistent.',
        satisfactory: 'Slides are readable but cluttered or inconsistent.',
        insufficient: 'Slides hinder rather than support the pitch.',
        weight: 15,
      },
    ],
  },
]

export const seedMilestones: Milestone[] = [
  {
    id: 'm1',
    title: 'Team Formation & Topic Selection',
    dueDate: '2025-05-05',
    completed: true,
    description: 'Form groups of 4–5. Submit your chosen company and innovation theme by end of week.',
  },
  {
    id: 'm2',
    title: 'Initial Stakeholder Map',
    dueDate: '2025-05-14',
    completed: true,
    description: 'First draft of stakeholder map — discussed and refined in Session 2.',
  },
  {
    id: 'm3',
    title: 'Problem Framing Workshop',
    dueDate: '2025-05-21',
    completed: false,
    description: 'In-class workshop to sharpen your problem framing before the deliverable.',
  },
  {
    id: 'm4',
    title: 'Business Case — Problem Framing (Deliverable 1)',
    dueDate: '2025-06-02',
    completed: false,
    description: 'Submit via Canvas by 23:59. See the Criteria Transparency board for the rubric.',
  },
  {
    id: 'm5',
    title: 'Prototype Peer Review',
    dueDate: '2025-06-13',
    completed: false,
    description: 'In-class peer review of prototype concepts. Prepare a 2-minute walk-through.',
  },
  {
    id: 'm6',
    title: 'Prototype Pitch Presentation (Deliverable 2)',
    dueDate: '2025-06-20',
    completed: false,
    description: '10-minute pitch to the panel. See Criteria Transparency board for assessment criteria.',
  },
]
